api         =       "/api"
inventory   = api + "/inventory"
brew        = api + "/brew"
brew_post   = brew+ "/write"
batch       = api + "/batch"
product     = api + "/product"
machine     = api + "/machine"
admin       = api + "/admin"
